name: Build on PR
on:
  # This workflow will only run for pull requests targeting the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      # Remember we have to check out the repository first!
      - name: Checkout repository
        uses: actions/checkout@v5

      # This step installs the dependencies
      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Generate version
        id: version
        run: echo "version=1.2.3" >> $GITHUB_OUTPUT

      - name: Use version in same job
        run: echo "Version is ${{ steps.version.outputs.version }}"

  test:
    name: Test Project
    runs-on: ubuntu-latest
    steps:
      # Remember we have to check out the repository first!
      - name: Checkout repository
        uses: actions/checkout@v5

      # This step installs the dependencies
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy version
        run: echo "Deploying version ${{ needs.build.outputs.version }}"