name: Pull Request Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  say-hello:
    name: Say Hello

    runs-on: ubuntu-latest

    steps:
      - name: Print greeting
        run: echo "Hello, Pull Request!"

